  name: itool release

  on:
    push:
      tags:
        - v*
      branches:
        - master
  jobs:
    release:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os:
            - ubuntu-latest
            - macOS-latest
          version:
            - latest
            - '~> 0.182'
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.18
        - name: Create release on Github
          uses: goreleaser/goreleaser-action@v2
          with:
            version: ${{ matrix.version }}
            args: release --rm-dist
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}